# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUP9IqIhLgoFqktGhrxZnHVRsQdW4eeQ
"""

def soma():
    n1 = 10
    n2 = 25
    total = n1+n2
    print(total)

def soma(n1,n2):
    total = n1+n2
    print(total)

soma(10,20)

total = soma(100,200)
print(total)

def maior_valor(valores):
    return max(valores)

def capturar_numeros():
    lista_numeros = []
    while True:
        numero = int(input('informe o numero inteiro e zero para sair'))
        if numero <= 0:
            break
        lista_numeros.append(numero)
    print('o maior numero adicionado a lista foi: ')
    return maior_valor(lista_numeros)

capturar_numeros()

import random,sys,os,math

valor = 100.00
def calculo():
    valor = 50.00
    print(valor)

taxa_juros = 1.2/100
def calculo1(n1,n2):
    total = n1+n2
    total *= taxa_juros
    print(f'calculo 1: {total}')

def calculo2(n1):
    total = 0
    for valor in n1:
        total+=valor
    total+=total*taxa_juros
    print(f'calcule 2: {total}')

import numpy as np

class lista_ordenada:
    def __init__(self, capacidade):
        self.capacidade = capacidade
        self.ultima_posicao = -1
        self.valores = np.empty(self.capacidade, dtype = int)
    
    #0(n)
    def imprime(self):
        if self.ultima_posicao == -1:
            print('o valor esta vazio')
        else:
            for i in range(self.ultima_posicao + 1):
                print(i, '-', self.valores[i])
    
    def insere(self, valor):
        if self.ultima_posicao == self.capacidade - 1:
            print('capacidade maxima atingida')
            return
        posicao = 0
        for i in rang(self.ultima_posicao):
            posicao = i 
            if self.valores[i] > valor:
                break
            x=self.ultima_posicao
            while x>=posicao:
                self.valores[x+1] = self.valores
                x=-1
                self.valores[posicao]  = valor
                self.ultima_posicao +=1

l=[1,2,3,4,5,6,7,8,9,10]
l[-1]

l=[1,2,3,4,5,6,7,8,9,10]
a=23
l.insert(-1,a)
l